name: Java CI-CD with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Copy jar file to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: './target/AttendanceLog.jar'
          remote: '/home/attendance_log/AttendanceLog.jar'
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          
      - name: Run jar file
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: java -jar /home/attendance_log/AttendanceLog.jar -xms200M -xmx768M &
          host: ${{ secrets.HOST }}
          port: 22
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          args: "-tt"       
          
